sudo: false

cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.4'
      env: TOXENV=py34
    - python: '2.7'
      env: TOXENV=py27
    - python: 'pypy'
      env: TOXENV=pypy
    - python: '3.6'
      env: TOXENV=py2,py3,coverage
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=lint

install: pip install tox

script: tox
